#!/usr/bin/env bash
# This adds a header to display which server running
sudo chmod a+w /etc/nginx/sites-enabled/default
sedCommand="server_name _;
	add_header X-Served-By $hostname;"
sudo sed $sedCommand >> /etc/nginx/sites-enabled/default
