#!/usr/bin/env bash
# This adds a header to display which server running
sudo chmod a+w /etc/nginx/sites-enabled/default
sudo echo "\nserver {\n\tadd_header X-Served-By \$hostname;\n}\n" >> /etc/nginx/sites-enabled/default
