#!/usr/bin/env bash
# This script creates a .pid file and adds commands in it

touch /var/run/myscript.pid
echo $$ > /var/myscript.pid
pidfile=/var/myscript.pid

trap "echo 'I hate the kill command' sudo pkill -f 100-process_and_pid_file" 9
trap "echo Y U no love me?!" 2
trap "rm $pidfile" 15
trap "rm $pidfile" 3

i=1
while [ "$i" -lt 10 ]
do
    echo "To infinity and beyond"
    sleep 2
done
