#!/usr/bin/env bash

string1=initialized
if [ -n $string1 ]    # string1 has not been declared or initialized.
then
  echo "String \"string1\" is not null."
else
  echo "String \"string1\" is null."
fi

echo "$string1"
